<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd8ab09fafac53bceb56f69ead1a4d644
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Tawk\\Tests\\' => 11,
            'Tawk\\' => 5,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Tawk\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/tawk/url-utils/tests',
        ),
        'Tawk\\' => 
        array (
            0 => __DIR__ . '/..' . '/tawk/url-utils/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd8ab09fafac53bceb56f69ead1a4d644::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd8ab09fafac53bceb56f69ead1a4d644::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd8ab09fafac53bceb56f69ead1a4d644::$classMap;

        }, null, ClassLoader::class);
    }
}
