<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Tawk\\Tests\\' => array($vendorDir . '/tawk/url-utils/tests'),
    'Tawk\\' => array($vendorDir . '/tawk/url-utils/lib'),
);
